import { GoogleGenerativeAI } from '@google/generative-ai';
import { config } from '../config/index.js';

/* ── Gemini client (lazy — only initialised when a key is present) ─── */
let _genAI: GoogleGenerativeAI | null = null;
function getClient() {
  if (!config.geminiApiKey) throw new Error('GEMINI_API_KEY is not configured');
  if (!_genAI) _genAI = new GoogleGenerativeAI(config.geminiApiKey);
  return _genAI;
}

/* ── Base system prompt shared across all AI features ─────────────── */
const ORION_SYSTEM_PROMPT = `
You are Orion AI — the intelligent assistant built into the Orion IoT Platform by Vortan (orion.vortan.io).

You produce precise, production-quality outputs. Every response must be deterministic and reproducible given the same inputs.
Never add explanations, markdown prose, or commentary outside of code comments.
`.trim();

/* ── Codegen-specific system prompt ───────────────────────────────── */
const CODEGEN_SYSTEM_PROMPT = `
${ORION_SYSTEM_PROMPT}

## ROLE
You are Orion Firmware Generator. You write embedded firmware that connects hardware to the Orion IoT platform.

## ORION API CONTRACT
- Telemetry endpoint: POST {API_BASE}/api/v1/telemetry/ingest
- Authentication: HTTP header  X-API-Key: {DEVICE_API_KEY}
- Content-Type: application/json
- Payload: flat JSON — sensor readings as top-level numeric/string/boolean keys
  Example: {"temperature": 22.5, "humidity": 65, "door_open": true}
- Reserved keys (never send as telemetry): api_key, timestamp, device_id
- Response: {"ok": true, "ts": "...", "command": {...}}  — command may be null

## OUTPUT RULES
1. Output ONLY raw source code. No markdown fences, no prose, no explanations.
2. First block must be the file header comment (see ORION STYLE below).
3. Data channel read functions must be STUBS — they accept and return the measured value unchanged.
   The user fills in the real sensor logic. Mark each with: // TODO: read your sensor here
4. Use the exact API_BASE, DEVICE_API_KEY, and field names provided in the user prompt.
5. Do not invent field names. Use only the ones listed in "DATA FIELDS".

## ORION CODING STYLE
\`\`\`
/*
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  Generated by Orion · orion.vortan.io · {ISO_DATE}              ║
 * ║  Device : {DEVICE_NAME}                                         ║
 * ║  Hardware: {HARDWARE_LABEL}                                     ║
 * ║  DO NOT commit API keys to version control.                     ║
 * ╚══════════════════════════════════════════════════════════════════╝
 */
\`\`\`

Section separators: /* ================= SECTION NAME ================= */
Sections (in order): CONFIG, PINS, DATA CHANNELS, NETWORK, MAIN

## STUB PATTERN
float read_temperature(float measured) {
  // TODO: read your sensor here
  return measured;
}

## HARDWARE KNOWLEDGE
When the target is ESP32 + SIMCom GSM via PPP:
- Use the Arduino-esp32 PPP library (PPP.h, PPPOS.h, PPPOSClient.h)
- PPP_MODEM_SIM800 for SIM800/SIM800L/SIM800C
- PPP_MODEM_SIM7600 for SIM7600/SIM7000/A7670
- Pattern: modem_reset → PPP.begin → wait attached → PPP.mode(DATA) → waitStatusBits → setupDNS
- Always set DNS manually after PPP connects (8.8.8.8 / 1.1.1.1)
- On ESP32 deep-sleep: disable WiFi, BT, put modem to AT+CSCLK=2 before sleep

When the target is ESP32 + WiFi:
- Use WiFi.h, HTTPClient.h
- Non-blocking reconnect pattern in loop

When the target is ESP32 + GSM via AT commands (no PPP):
- Use Software or Hardware Serial to talk to modem via AT
- Sequence: AT+SAPBR (GPRS context) → AT+HTTPINIT → AT+HTTPPARA → AT+HTTPDATA → AT+HTTPACTION

When the target is Arduino (Uno/Mega/Nano) + SIM800 via AT:
- Use SoftwareSerial or HardwareSerial for modem
- Same AT sequence as above but account for limited RAM (avoid String class, use char[])

When the target is Raspberry Pi Pico W (MicroPython):
- Use urequests for HTTP
- Use machine.deepsleep for low power
`.trim();

/* ── Report-generation system prompt (stub — extend later) ────────── */
const REPORT_SYSTEM_PROMPT = `
${ORION_SYSTEM_PROMPT}

## ROLE
You are Orion Report Writer. You analyse IoT telemetry data and produce a concise, human-readable diagnostic report.

## OUTPUT FORMAT
Return a JSON object with this exact shape:
{
  "title": "string — short report title",
  "summary": "string — 2-3 sentence executive summary",
  "insights": ["string", ...],   // 3-5 bullet points
  "anomalies": ["string", ...],  // any unusual patterns, empty array if none
  "recommendation": "string"     // one actionable next step
}
Output ONLY valid JSON. No markdown, no prose outside the JSON.
`.trim();

/* ── Public API ───────────────────────────────────────────────────── */
export interface CodeGenRequest {
  deviceName: string;
  deviceApiKey: string;
  apiBase: string;
  hardware: string;
  hardwareLabel: string;
  fields: Array<{ key: string; unit?: string }>;
  config: Record<string, string | number>;
}

export interface ReportRequest {
  deviceName: string;
  fields: Array<{ key: string; values: number[]; unit?: string }>;
  periodLabel: string;
}

export const aiService = {

  isConfigured() {
    return !!config.geminiApiKey;
  },

  async generateFirmware(req: CodeGenRequest): Promise<string> {
    const model = getClient().getGenerativeModel({
      model: 'gemini-2.0-flash',
      systemInstruction: CODEGEN_SYSTEM_PROMPT,
    });

    const fieldList = req.fields.length
      ? req.fields.map(f => `  - ${f.key}${f.unit ? ` (${f.unit})` : ''}`).join('\n')
      : '  (no schema defined — use placeholder fields)';

    const cfgList = Object.entries(req.config)
      .map(([k, v]) => `  ${k}: ${v}`)
      .join('\n');

    const userPrompt = `
Generate complete firmware for the following device.

DEVICE NAME: ${req.deviceName}
HARDWARE: ${req.hardwareLabel}
API_BASE: ${req.apiBase}
DEVICE_API_KEY: ${req.deviceApiKey}
SEND_INTERVAL_SECONDS: ${req.config.intervalSeconds ?? 60}
ISO_DATE: ${new Date().toISOString().slice(0, 10)}

DATA FIELDS (these are the exact JSON keys to send):
${fieldList}

HARDWARE CONFIG:
${cfgList}

Produce a single complete source file ready to flash.
`.trim();

    const result = await model.generateContent(userPrompt);
    let code = result.response.text().trim();

    // Strip markdown fences if the model wraps the output anyway
    code = code.replace(/^```[\w]*\n?/m, '').replace(/\n?```$/m, '').trim();
    return code;
  },

  async generateReport(req: ReportRequest): Promise<object> {
    const model = getClient().getGenerativeModel({
      model: 'gemini-2.0-flash',
      systemInstruction: REPORT_SYSTEM_PROMPT,
    });

    const fieldSummaries = req.fields.map(f => {
      const vals = f.values;
      if (!vals.length) return `${f.key}: no data`;
      const mn = Math.min(...vals).toFixed(2);
      const mx = Math.max(...vals).toFixed(2);
      const avg = (vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(2);
      return `${f.key}${f.unit ? ` (${f.unit})` : ''}: min=${mn} max=${mx} avg=${avg} samples=${vals.length}`;
    }).join('\n');

    const userPrompt = `
Device: ${req.deviceName}
Period: ${req.periodLabel}

Telemetry summary:
${fieldSummaries}
`.trim();

    const result = await model.generateContent(userPrompt);
    const text = result.response.text().trim().replace(/^```json\n?/, '').replace(/\n?```$/, '');
    return JSON.parse(text);
  },
};
