import { GoogleGenerativeAI } from '@google/generative-ai';
import { config } from '../config/index.js';

/* ── Gemini client (lazy) ──────────────────────────────────────────── */
let _genAI: GoogleGenerativeAI | null = null;
function getClient() {
  if (!config.geminiApiKey) throw new Error('Orion AI is not configured');
  if (!_genAI) _genAI = new GoogleGenerativeAI(config.geminiApiKey);
  return _genAI;
}

/* ── Sliding-window rate limiter (14 req/min, free tier = 15) ─────── */
class RateLimiter {
  private slots: number[] = [];
  private readonly limit: number;

  constructor(limit = 14) { this.limit = limit; }

  get waiting(): number { return Math.max(0, this.slots.length - this.limit + 1); }

  async claim(): Promise<void> {
    while (true) {
      const now = Date.now();
      this.slots = this.slots.filter(t => now - t < 60_000);
      if (this.slots.length < this.limit) {
        this.slots.push(now);
        return;
      }
      const sleepMs = this.slots[0] + 60_000 - now + 300;
      await new Promise(r => setTimeout(r, Math.max(300, sleepMs)));
    }
  }
}

export const rateLimiter = new RateLimiter(14); // Gemini free tier: 15 req/min

/* ── Base system prompt ────────────────────────────────────────────── */
const ORION_SYSTEM_PROMPT = `
You are Orion AI — the intelligent assistant built into the Orion IoT Platform by Vortan (orion.vortan.io).

You produce precise, production-quality outputs. Every response must be deterministic and reproducible given the same inputs.
Never add explanations, markdown prose, or commentary outside of code comments.
`.trim();

/* ── Codegen system prompt ─────────────────────────────────────────── */
const CODEGEN_SYSTEM_PROMPT = `
${ORION_SYSTEM_PROMPT}

## ROLE
You are Orion Firmware Generator. You write embedded firmware that connects hardware to the Orion IoT platform.

## OUTPUT RULES
1. Output ONLY raw source code. No markdown fences, no prose, no explanations.
2. First block must be the file header comment (see ORION STYLE below).
3. Data channel read functions must be STUBS — accept and return the measured value unchanged.
   Mark each with: // TODO: read your sensor here
4. Use the exact credentials and field names provided in the user prompt.
5. Do not invent field names. Use only the ones listed in DATA FIELDS.
6. The PROTOCOL in the user prompt dictates the transport. Use ONLY that protocol — never mix transports.

## ORION CODING STYLE
/*
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  Generated by Orion · orion.vortan.io · {ISO_DATE}              ║
 * ║  Device : {DEVICE_NAME}                                         ║
 * ║  Hardware: {HARDWARE_LABEL}                                     ║
 * ║  Protocol: {PROTOCOL}                                           ║
 * ║  DO NOT commit credentials to version control.                  ║
 * ╚══════════════════════════════════════════════════════════════════╝
 */

Section separators: /* ================= SECTION NAME ================= */
Sections (in order): CONFIG, PINS, DATA CHANNELS, NETWORK, MAIN

## STUB PATTERN
float read_temperature(float measured) {
  // TODO: read your sensor here
  return measured;
}

## PROTOCOL CONTRACTS

### HTTP
- POST {API_BASE}/api/v1/telemetry/ingest
- Header: X-API-Key: {DEVICE_API_KEY}
- Content-Type: application/json
- Body: flat JSON of sensor readings
- Response: {"ok":true,"ts":"...","command":{...}} — command may be null; handle it

### MQTT
- Broker: {MQTT_BROKER}  Port: 1883
- Telemetry topic  (publish QoS 1): /{SERIAL}/data
- Command topic    (subscribe):      /{SERIAL}/commands
- Command ack      (publish):        /{SERIAL}/commands/{commandId}/ack
- Client ID: use DEVICE_SERIAL or a unique random suffix
- Payload: flat JSON of sensor readings — NO api_key field required
- On command message: parse JSON, execute, publish {"commandId":"...","status":"executed"} to ack topic

### TCP
- Connect to {API_HOST}:{TCP_PORT}
- Send newline-terminated: {DEVICE_API_KEY}|{JSON_PAYLOAD}\\n
- Keep connection alive between sends or reconnect each cycle

### UDP
- Send datagram to {API_HOST}:{UDP_PORT}
- Format: {DEVICE_API_KEY}|{JSON_PAYLOAD}

### CoAP
- POST coap://{API_HOST}:{COAP_PORT}/telemetry?apiKey={DEVICE_API_KEY}
- Payload: flat JSON

### WebSocket
- Connect: ws://{API_HOST}/ws?apiKey={DEVICE_API_KEY}
- Send: JSON object with sensor readings

## HARDWARE KNOWLEDGE

### Espressif + WiFi (Arduino framework)
- WiFi.h for connectivity; HTTPClient.h for HTTP; PubSubClient.h for MQTT
- Non-blocking WiFi reconnect in loop()
- For MQTT: PubSubClient client(wifiClient); topic strings from CONFIG section

### Espressif + SIMCom (PPP, Arduino-esp32)
- PPP.h / PPPOS.h from Arduino-esp32 ≥ 3.x
- PPP_MODEM_SIM800 for SIM800/SIM800L/SIM800C
- PPP_MODEM_SIM7600 for SIM7600/SIM7000/A7670
- Sequence: modem_reset → PPP.begin(model,rx,tx,rst) → wait PPP.attached() → PPP.mode(ESP_NETIF_PPP_MODE_DATA) → waitStatusBits → setDNS(8.8.8.8,1.1.1.1)
- After PPP up: use HTTPClient / PubSubClient exactly as WiFi variant — network is transparent
- Deep-sleep: AT+CSCLK=2 before esp_deep_sleep_start()

### Espressif + SIMCom (AT commands, no PPP)
- HardwareSerial(1) or SoftwareSerial for modem
- HTTP sequence: AT+SAPBR=3,1,"Contype","GPRS" → AT+SAPBR=3,1,"APN","{apn}" → AT+SAPBR=1,1 → AT+HTTPINIT → AT+HTTPPARA → AT+HTTPDATA → AT+HTTPACTION=1 → AT+HTTPREAD → AT+HTTPTERM → AT+SAPBR=0,1
- MQTT sequence: AT+MQTTUSERCFG → AT+MQTTCONN → AT+MQTTPUB / AT+MQTTSUB

### Arduino framework + SIMCom (AT commands)
- SoftwareSerial for modem (avoid String class — use char[] to save RAM)
- Same AT HTTP/MQTT sequences as Espressif AT variant
- Account for limited SRAM: pre-allocate buffers in PROGMEM where possible

### Raspberry Pi (MicroPython)
- HTTP: urequests.post(url, json={...}, headers={"X-API-Key":KEY})
- MQTT: from umqtt.simple import MQTTClient
- Deep sleep: machine.deepsleep(ms)
- main.py entry point; run forever in while True loop with time.sleep(interval)
`.trim();

/* ── Report system prompt ──────────────────────────────────────────── */
const REPORT_SYSTEM_PROMPT = `
${ORION_SYSTEM_PROMPT}

## ROLE
You are Orion Report Writer. You analyse IoT telemetry data and produce a concise, human-readable diagnostic report.

## OUTPUT FORMAT
Return a JSON object with this exact shape:
{
  "title": "string — short report title",
  "summary": "string — 2-3 sentence executive summary",
  "insights": ["string", ...],
  "anomalies": ["string", ...],
  "recommendation": "string"
}
Output ONLY valid JSON. No markdown, no prose outside the JSON.
`.trim();

/* ── Public types ──────────────────────────────────────────────────── */
export interface CodeGenRequest {
  deviceName: string;
  deviceApiKey: string;
  serialNumber: string;
  apiBase: string;
  apiHost: string;
  mqttBroker: string;
  tcpPort: number;
  udpPort: number;
  coapPort: number;
  protocol: string;
  hardware: string;
  hardwareLabel: string;
  fields: Array<{ key: string; unit?: string }>;
  config: Record<string, string | number>;
}

export interface ReportRequest {
  deviceName: string;
  fields: Array<{ key: string; values: number[]; unit?: string }>;
  periodLabel: string;
}

/* ── Shared prompt builder ─────────────────────────────────────────── */
function buildFirmwarePrompt(req: CodeGenRequest): string {
  const fieldList = req.fields.length
    ? req.fields.map(f => `  - ${f.key}${f.unit ? ` (${f.unit})` : ''}`).join('\n')
    : '  (no schema defined — use generic placeholder fields)';

  const cfgList = Object.entries(req.config)
    .map(([k, v]) => `  ${k}: ${v}`)
    .join('\n');

  return `
Generate complete firmware for the following device.

DEVICE_NAME: ${req.deviceName}
HARDWARE: ${req.hardwareLabel}
PROTOCOL: ${req.protocol.toUpperCase()}
ISO_DATE: ${new Date().toISOString().slice(0, 10)}

CREDENTIALS:
  DEVICE_API_KEY: ${req.deviceApiKey}
  DEVICE_SERIAL: ${req.serialNumber}

ENDPOINTS:
  API_BASE: ${req.apiBase}
  API_HOST: ${req.apiHost}
  MQTT_BROKER: ${req.mqttBroker}
  TCP_PORT: ${req.tcpPort}
  UDP_PORT: ${req.udpPort}
  COAP_PORT: ${req.coapPort}

DATA FIELDS (exact JSON keys to send):
${fieldList}

HARDWARE CONFIG:
${cfgList}

Produce a single complete source file. Use ONLY the ${req.protocol.toUpperCase()} protocol.
`.trim();
}

/* ── Service ───────────────────────────────────────────────────────── */
export const aiService = {

  isConfigured() {
    return !!config.geminiApiKey;
  },

  async generateFirmware(req: CodeGenRequest): Promise<string> {
    await rateLimiter.claim();
    const model = getClient().getGenerativeModel({
      model: 'gemini-2.0-flash',
      systemInstruction: CODEGEN_SYSTEM_PROMPT,
    });
    const result = await model.generateContent(buildFirmwarePrompt(req));
    let code = result.response.text().trim();
    code = code.replace(/^```[\w]*\n?/m, '').replace(/\n?```$/m, '').trim();
    return code;
  },

  async *generateFirmwareStream(
    req: CodeGenRequest,
    onWait?: (seconds: number) => void,
  ): AsyncGenerator<string> {
    const model = getClient().getGenerativeModel({
      model: 'gemini-2.0-flash',
      systemInstruction: CODEGEN_SYSTEM_PROMPT,
    });
    const prompt = buildFirmwarePrompt(req);

    const MAX_RETRIES = 3;
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        await rateLimiter.claim();
        const result = await model.generateContentStream(prompt);
        for await (const chunk of result.stream) {
          const text = chunk.text();
          if (text) yield text;
        }
        return; // success
      } catch (err: any) {
        // GoogleGenerativeAIFetchError has .status; fall back to message scan
        const status: number =
          err?.status ??
          err?.response?.status ??
          (typeof err?.message === 'string' && /\b429\b/.test(err.message) ? 429 : 0);

        console.error(`[OrionAI] attempt ${attempt + 1} failed — status=${status} message=${err?.message}`);

        if (status === 429 && attempt < MAX_RETRIES) {
          const waitSeconds = 65;
          if (onWait) onWait(waitSeconds);
          await new Promise(r => setTimeout(r, waitSeconds * 1000));
          continue;
        }
        throw err;
      }
    }
  },

  async generateReport(req: ReportRequest): Promise<object> {
    await rateLimiter.claim();
    const model = getClient().getGenerativeModel({
      model: 'gemini-2.0-flash',
      systemInstruction: REPORT_SYSTEM_PROMPT,
    });

    const fieldSummaries = req.fields.map(f => {
      const vals = f.values;
      if (!vals.length) return `${f.key}: no data`;
      const mn = Math.min(...vals).toFixed(2);
      const mx = Math.max(...vals).toFixed(2);
      const avg = (vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(2);
      return `${f.key}${f.unit ? ` (${f.unit})` : ''}: min=${mn} max=${mx} avg=${avg} samples=${vals.length}`;
    }).join('\n');

    const userPrompt = `Device: ${req.deviceName}\nPeriod: ${req.periodLabel}\n\nTelemetry summary:\n${fieldSummaries}`;
    const result = await model.generateContent(userPrompt);
    const text = result.response.text().trim()
      .replace(/^```json\n?/, '').replace(/\n?```$/, '');
    return JSON.parse(text);
  },
};
